global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gateway'
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - 'agent_gateway:10086'
          - 'agent_gateway2:10086'
          - 'agent_gateway3:10086'
          - 'agent_gateway4:10086'
rule_files:
  - "alert.rules.yml"
